# Generated by Django 4.0.3 on 2022-03-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('sequence', models.CharField(max_length=3440)),
            ],
        ),
    ]
