# Generated by Django 4.0.3 on 2022-03-24 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_sequence_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
