# Generated by Django 4.0.3 on 2022-03-25 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sequence_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='tree',
            field=models.CharField(default=django.utils.timezone.now, max_length=6440),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sequence',
            name='sequence',
            field=models.CharField(max_length=6440),
        ),
    ]
