# Generated by Django 4.0.3 on 2022-03-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_sequence_tree_alter_sequence_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
