# Generated by Django 4.0.3 on 2022-03-29 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_sequence_one_sequence_length_sequence_sequence_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='options',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
