# Generated by Django 4.0.3 on 2022-03-31 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_sequence_seq_showcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='seq_showcase',
        ),
    ]
