# Generated by Django 4.0.3 on 2022-04-11 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_sequence_seq_showcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='phyloxmltree',
            field=models.CharField(default=django.utils.timezone.now, max_length=712364),
            preserve_default=False,
        ),
    ]
